### ISSUE TITLE
SIW.php : "avisar todos" > lista de editores apresentada

### ISSUE THREAD

**Issue by A-Infor** [albertoleoncio/alberobot#18]
A lista de editores apresentada por SIW.php tem sempre menos editores do que quando se clica em "Avisar todos".

https://alberobot.toolforge.org/siw.php?artigo_titulo=Intraculturalismo lista 4 editores, mas ao "avisar todos" abre 8 abas.

**Comment by A-Infor** [comment]
Apontado por Stego que a lista de desinscrição está sendo ignorada ao usar o botão "Avisar todos". **Mea culpa.**
https://pt.wikipedia.org/w/index.php?title=Usu%C3%A1rio_Discuss%C3%A3o:MisterSanderson&diff=62501167&oldid=62501094&diffmode=source

**Comment by albertoleoncio** [comment]
Aparentemente resolvido
