### ISSUE TITLE
SIW.php : envio avisos a mim mesmo

### ISSUE THREAD

**Issue by A-Infor** [albertoleoncio/alberobot#24]
O editor que abre o SIW.php passa o parâmetro na URL: `?artigo_titulo=X`, mas não passa o parâmetro de seu próprio nome para ser excluído da lista de editores a serem avisados.

Me parece natural que o editor não precise avisar a si mesmo. O que pensas?

**Comment by albertoleoncio** [comment]
Complexo, já que o script não sabe qual o nome do usuário que irá enviar as mensagens. Pedir para que o usuário informe seu próprio nome na ferramenta apenas para evitar que o usuário envie o aviso para ele mesmo parece-me contraproducente. É melhor que o usuário apenas olhe para quem está enviando as mensagens na hora de clicar no "publicar".

**Comment by A-Infor** [comment]
@albertoleoncio O script não tem como adivinhar o nome. Mas o usuário está logado na Wikipédia, e é de lá que é gerado o link que informa o nome do artigo. Esse link não poderia informar o nome do usuário também?

**Comment by albertoleoncio** [comment]
> @albertoleoncio O script não tem como adivinhar o nome. Mas o usuário está logado na Wikipédia, e é de lá que é gerado o link que informa o nome do artigo. Esse link não poderia informar o nome do usuário também?

Não funciona assim. O link serve para apenas "dizer" para a wiki que aquele texto ali deve ser inserido abaixo do texto atual, e ele leva apenas o nome do artigo como parâmetro. Se ele levasse o nome do usuário que estivesse enviando o aviso, ele teria que ser informado na própria ferramenta, o que não vale a pena.

Mesmo assim, pensei em duas possibilidades que não deram muito certo. Uma delas e envolver a [mensagem](https://pt.wikipedia.org/w/index.php?title=Predefini%C3%A7%C3%A3o:Aviso-ESR-SIW) em uma if, tipo isso:
`{{<includeonly>safesubst:</includeonly>#ifeq:{{REVISIONUSER}}|{{ROOTPAGENAME}}||...conteúdo...}}`
só que o MediaWiki utiliza o nome do último usuário que editou a página na hora de fazer o subst, e não o usuários atual, então não funciona.

Outra opção é usar o próprio nome de usuário que vem na assinatura, tipo isso:
`{{<includeonly>safesubst:</includeonly>#ifeq:~~~|[[Usuário(a):{{ROOTPAGENAME}}|{{ROOTPAGENAME}}]]||...conteúdo...}}`
mas isso exigiria que a assinatura do usuário estivesse idêntica ao padrão inicial, que é uma coisa que poucos usuários experientes mantem.

**Comment by A-Infor** [comment]
> Não funciona assim. O link serve para apenas "dizer" para a wiki que aquele texto ali deve ser inserido abaixo do texto atual, e ele leva apenas o nome do artigo como parâmetro. Se ele levasse o nome do usuário que estivesse enviando o aviso, ele teria que ser informado na própria ferramenta, o que não vale a pena.

Acho que não estamos falando do mesmo link, pois o que me refiro não "serve para dizer para a wiki que aquele texto deve ser inserido abaixo do atual".

Me referi a este link, que grifei com marca-texto:
![link](https://user-images.githubusercontent.com/67929816/158345422-17970a24-c4f1-49e9-8fd8-03d449968a99.PNG)

Ele gera a seguinte URL, que só tem por parâmetro o nome do artigo:
![link 2](https://user-images.githubusercontent.com/67929816/158345467-d0d48dc5-6c27-49b0-96b3-ab8a1886b532.png)

**Comment by A-Infor** [comment]
Resolvi acidentalmente: incluí meu nome na Lista de Descadastro e agora não recebo mais avisos de ninguém, inclusive de mim mesmo. Quem se sentir incomodado de avisar a si mesmo pode seguir esse mesmo caminho.
