### ISSUE TITLE
Aspas no título do artigo quebram o funcionamento do programa

### ISSUE THREAD

**Issue by A-Infor** [albertoleoncio/alberobot#35]
O artigo https://pt.wikipedia.org/wiki/Brian_%22Beast%22_East gerou o seguinte erro ao ser clicado no link "[Verificar lista de usuários](https://alberobot.toolforge.org/siw.php?artigo_titulo=Brian+%26%2334%3BBeast%26%2334%3B+East), presente da etiqueta de eliminação:
![imagem](https://user-images.githubusercontent.com/67929816/215202956-6c174919-d02d-4bf7-9a78-ed9990c9dd55.png)

**Comment by albertoleoncio** [comment]
Era mais um problema do MediaWiki do que da ferramenta. Resolvi com [essa alteração na prefedinição](https://pt.wikipedia.org/w/index.php?diff=65197148) e o commit a seguir.
